version: "2.23.3"
services:
  jsapi:
   build: ./jsApi-docker-sample
   container_name: jsapi_c
   ports:
    - '4000:4000'
   volumes:
    - ./jsApi-docker-sample:/jsapi_sample
    - ${PWD}/jsapi_sample/node_modules
